#!/usr/bin/env python3
"""
make_drone.py: build our drone model from config/drone.yaml.

Writes two Gazebo models into aware_sim/models/:
  aware_cam/    a copy of PX4's mono_cam, with OUR rate (and lens settings)
  aware_x500/   PX4's x500 frame (included as-is) + aware_cam at OUR tilt

Then links both into PX4's model folder (like we did for the world), because
PX4 spawns vehicles from there. PX4's own files are not modified.

    python3 make_drone.py                 # build + link
    python3 make_drone.py --no-link       # build only
"""
import argparse
import math
import os
import sys
from pathlib import Path

import yaml

PKG_DIR = Path(__file__).resolve().parent.parent
MODELS = PKG_DIR / "models"

CAM_SDF = """<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by make_drone.py from config/drone.yaml. Copy of PX4's mono_cam;
     only update_rate (and lens settings, if changed) differ. -->
<sdf version="1.9">
  <model name="aware_cam">
    <pose>0 0 0 0 0 0</pose>
    <self_collide>false</self_collide>
    <static>false</static>
    <link name="camera_link">
      <inertial>
        <pose>0.03 0.03 0.03 0 0 0</pose>
        <mass>0.050</mass>
        <inertia>
          <ixx>0.00004</ixx><ixy>0</ixy><ixz>0</ixz>
          <iyy>0.00004</iyy><iyz>0</iyz><izz>0.00004</izz>
        </inertia>
      </inertial>
      <visual name="housing">
        <geometry><box><size>0.02 0.04 0.04</size></box></geometry>
      </visual>
      <visual name="lens">
        <pose>0.015 0 0 0 1.5707 0</pose>
        <geometry><cylinder><radius>0.008</radius><length>0.01</length></cylinder></geometry>
      </visual>
      <sensor name="camera" type="camera">
        <gz_frame_id>camera_link</gz_frame_id>
        <pose>0 0 0 0 0 0</pose>
        <camera>
          <horizontal_fov>{hfov}</horizontal_fov>
          <image><width>{width}</width><height>{height}</height></image>
          <clip><near>0.1</near><far>{far}</far></clip>
        </camera>
        <always_on>1</always_on>
        <update_rate>{rate}</update_rate>
        <visualize>true</visualize>
      </sensor>
      <gravity>true</gravity>
      <velocity_decay />
    </link>
  </model>
</sdf>
"""

DRONE_SDF = """<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by make_drone.py from config/drone.yaml.
     Same structure as PX4's x500_mono_cam_down, but with OUR camera and OUR tilt.
     Camera pitch {pitch_deg} deg below the horizon = {pitch_rad:.4f} rad
     (a Gazebo camera looks along its x-axis; pitching it down by +angle tilts it). -->
<sdf version="1.9">
  <model name="{name}">
    <self_collide>false</self_collide>
    <include merge="true">
      <uri>model://x500</uri>
    </include>
    <include merge="true">
      <uri>model://aware_cam</uri>
      <pose>{ox} {oy} {oz} 0 {pitch_rad:.4f} 0</pose>
      <name>aware_cam</name>
    </include>
    <joint name="CameraJoint" type="fixed">
      <parent>base_link</parent>
      <child>camera_link</child>
      <pose relative_to="base_link">0 0 0 0 {pitch_rad:.4f} 0</pose>
    </joint>
  </model>
</sdf>
"""

CONFIG = """<?xml version="1.0"?>
<model>
  <name>{name}</name>
  <version>1.0</version>
  <sdf version="1.9">model.sdf</sdf>
  <description>{desc}</description>
</model>
"""


def write_model(name, sdf, desc):
    d = MODELS / name
    d.mkdir(parents=True, exist_ok=True)
    (d / "model.sdf").write_text(sdf)
    (d / "model.config").write_text(CONFIG.format(name=name, desc=desc))
    return d


def link_into_px4(model_dir, px4_models):
    link = px4_models / model_dir.name
    if link.is_symlink():
        link.unlink()                      # refresh an old link
    elif link.exists():
        sys.exit(f"{link} exists and is NOT our link. Refusing to touch PX4's files.")
    link.symlink_to(model_dir)
    return link


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--no-link", action="store_true")
    args = ap.parse_args()
    cfg = yaml.safe_load((PKG_DIR / "config" / "drone.yaml").read_text())
    cam = cfg["camera"]
    if not 0 <= cam["pitch_deg"] <= 90:
        sys.exit("camera.pitch_deg must be between 0 (ahead) and 90 (straight down)")

    cam_dir = write_model("aware_cam", CAM_SDF.format(
        hfov=cam["hfov_rad"], width=cam["width"], height=cam["height"],
        rate=cam["update_rate"], far=cam.get("far_clip_m", 3000)),
        "AWARE camera (copy of PX4 mono_cam)")
    ox, oy, oz = cam["mount_offset_m"]
    drone_dir = write_model(cfg["model_name"], DRONE_SDF.format(
        name=cfg["model_name"], pitch_deg=cam["pitch_deg"],
        pitch_rad=math.radians(cam["pitch_deg"]), ox=ox, oy=oy, oz=oz),
        "PX4 x500 frame + AWARE camera")

    print(f"Built {drone_dir.name}: camera {cam['pitch_deg']} deg below horizon, "
          f"{cam['width']}x{cam['height']} @ {cam['update_rate']} Hz, "
          f"renders up to {cam.get('far_clip_m', 3000)} m")

    # What the tilted camera sees (vertical field of view along the tilt)
    vfov = 2 * math.atan(math.tan(cam["hfov_rad"] / 2) * cam["height"] / cam["width"])
    top = cam["pitch_deg"] - math.degrees(vfov) / 2
    bottom = cam["pitch_deg"] + math.degrees(vfov) / 2
    print(f"  image top edge looks {top:.0f} deg below horizon, bottom edge {bottom:.0f} deg"
          + ("  (top edge above horizon: sky in the image)" if top < 0 else ""))
    for h in (10, 15, 20):
        far = h / math.tan(math.radians(top)) if top > 0 else float("inf")
        center = h / math.tan(math.radians(cam["pitch_deg"])) if cam["pitch_deg"] < 90 else 0
        print(f"  at {h} m: image center hits the ground {center:.0f} m ahead, "
              f"top edge {far:.0f} m ahead")

    if not args.no_link:
        root = os.environ.get("AWARE_ROOT")
        if not root:
            sys.exit("AWARE_ROOT is not set; cannot find PX4 (or use --no-link)")
        px4_models = Path(root) / "PX4-Autopilot" / "Tools" / "simulation" / "gz" / "models"
        for d in (cam_dir, drone_dir):
            print("  linked", link_into_px4(d, px4_models))
    print(f"\nPX4 model name: gz_{cfg['model_name']}   Gazebo instance: {cfg['model_name']}_0")


if __name__ == "__main__":
    main()
